#!/usr/bin/env bash
# Seed a small, realistic graph into a live c0 by driving real commands — so the
# integration test asserts against the actual write + embedding + index paths,
# not a hand-loaded fixture. Embeddings are generated by the real Ollama service.
#
# Usage: seed-test-graph.sh <namespace> <project-dir>
set -euo pipefail

NS="${1:-demo}"
PROJ="${2:-$PWD}"
FIXTURES="${C0_FIXTURES_DIR:-/c0/tests/fixtures}"
SESSION_ID="sess-demo-0001"
cd "$PROJ"

echo "── seeding concepts + relationships (namespace: $NS) ──"
# --force skips the similar-concept guard so near-neighbours seed deterministically.
c0 add concept "reciprocal rank fusion" -d "Rank-based fusion of multiple result lists; score = weight/(k+rank)." --force
c0 add concept "hybrid search" -d "Keyword (BM25) plus vector retrieval, fused by RRF." --force
c0 add concept "bm25" -d "Lexical ranking over term frequency and inverse document frequency." --force
c0 add concept "vector search" -d "Nearest-neighbour retrieval over embedding cosine similarity." --force

c0 relate "reciprocal rank fusion" USED_BY "hybrid search"
c0 relate "bm25" USED_BY "hybrid search"
c0 relate "vector search" USED_BY "hybrid search"

echo "── seeding a temporal supersession ──"
c0 add concept "pages router" -d "Next.js file-based routing under the pages directory." --force
c0 add concept "app router" -d "Next.js routing under the app directory with server components." --force
c0 supersede "pages router" --with "app router"

echo "── seeding an indexed session (real transcript -> turns + embeddings) ──"
mkdir -p "$HOME/.claude/projects/$NS"
cp "$FIXTURES/session-demo.jsonl" "$HOME/.claude/projects/$NS/$SESSION_ID.jsonl"
c0 sessions index

echo "── seed complete ──"
